### ISSUE TITLE
Game randomly crashes when Tesselating block in world

### ISSUE THREAD

**Issue by Mhowser** [LazuriteMC/Rayon#12]
Crashlog: https://0bin.net/paste/XX733xYQ#6xs9svYh-jLK1yIf6YtuTT3QycV1YV37kqXvdNE8Nfv

**Comment by ethanejohnsons** [comment]
Try out the new version [here ](https://www.curseforge.com/minecraft/mc-mods/dropz) and let me know if it still happens.

**Comment by Mhowser** [comment]
still crashes, although it looks like its a diffrent reason; https://0bin.net/paste/U8BkmWtR#-cc6/stwxRXFKpTGTkK8Bfnzd5La50PCxxPCtS7NnMf

**Comment by ethanejohnsons** [comment]
The first crash log you sent is due to a problem with Sodium which is currently being worked on. I will also look into the problem with your second crash log (it looks easier to fix, too).

**Comment by ethanejohnsons** [comment]
The issue with sodium should be resolved now.
