### ISSUE TITLE
Unreliable crash on world load

### ISSUE THREAD

**Issue by Devan-Kerman** [LazuriteMC/Rayon#27]
This occurs even without any rayon entities in the world, but only sometimes
[latest.log](https://github.com/LazuriteMC/Rayon/files/9173000/latest.log)

**Comment by ChemicallyEmo** [comment]
What does your crash report say? I have also been getting random crashes under this code.

Error: java.lang.RuntimeException: Failed to invoke onStartLevelTick in dev.lazurite.rayon.impl.event.ServerEventHandler$$Lambda$3656/0x0000000800b3c3e8.
Exit Code: -1

**Comment by Devan-Kerman** [comment]
I sent the log, and yes it's that or a similar error

**Comment by ethanejohnsons** [comment]
This should be resolved in [version 1.6.1](https://github.com/LazuriteMC/Rayon/releases/tag/1.6.1). Feel free to reopen this issue if the error presents itself again.

**Comment by Devan-Kerman** [comment]
Thanks!
