### ISSUE TITLE
rayon-forge-1.6.1.jar is marked as a Fabric release on CurseForge

### ISSUE THREAD

**Issue by floral-qua-floral** [LazuriteMC/Rayon#28]
[Link to the file on Curseforge](https://www.curseforge.com/minecraft/mc-mods/rayon/files/3918887)

![image](https://user-images.githubusercontent.com/49110090/183228984-88c259f7-370d-4100-9332-67a781ad515f.png)

The Modrinth versions seem to all be tagged properly, though.

**Comment by ethanejohnsons** [comment]
Should be fixed now. Thanks for letting me know.
